#!/usr/bin/env python
# coding: utf-8

# In[1]:


from geneformer import EmbExtractor


# In[ ]:


# initiate EmbExtractor
# OF NOTE: model_version should match version of model to be used (V1 or V2) to use the correct token dictionary
embex = EmbExtractor(model_type="Pretrained",
                     num_classes=0,
                     filter_data=None,
                     max_ncells=10000,
                     emb_layer=0,
                     emb_label=["condition","cell_type","cell_subtype","donor_id"],
                     labels_to_plot=["condition", "cell_subtype"],
                     forward_batch_size=200,
                     model_version="V1",  # OF NOTE: SET TO V1 MODEL, PROVIDE V1 MODEL PATH IN SUBSEQUENT CODE
                     nproc=8)

# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer (see tokenizing_scRNAseq_data.ipynb)
# example dataset for V1 model series: https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset
embs = embex.extract_embs("/d/projects/u/software/geneformer/content/Geneformer/Geneformer-V1-10M", # example V1 fine-tuned model
                          "tokenised_data/vpa_organoids.dataset",
                          "results",
                          "vpa_organoids_embeddings")


# In[4]:


# plot UMAP of cell embeddings
# note: scanpy umap necessarily saves figs to figures directory
embex.plot_embs(embs=embs, 
                plot_style="umap",
                output_directory="results",  
                output_prefix="emb_plot")


# In[5]:


# plot heatmap of cell embeddings
embex.plot_embs(embs=embs, 
                plot_style="heatmap",
                output_directory="results",
                output_prefix="emb_plot")


# In[ ]:




